version: '3.6'
services:
  server:
    container_name: c2wasm-api
    build: .
    restart: always
    ports:
      - "9000:9000"
    working_dir: /app
    command: [ "/sbin/su-exec", "appuser", "yarn", "dev" ]
    volumes:
      - ../c2wasm-api/src:/app/src
    environment:
      NODE_ENV: development
