name: c2wasm-api to Heroku CD

on:
  push:
    branches: [master, feat/dockerize-c2wasm-api]

#set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'xrpl-c2wasm-api' }}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:
      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download bin.zip
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "eqlabs/xrpl-hooks-compiler"
          version: "tags/v1.3"
          file: "bin.zio"
          target: "./plague-linux.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Download release
      #   uses: robinraju/release-downloader@v1.3
      #   with:
      #     repository: eqlabs/xrpl-hooks-compiler
      #     tag: "v1.3"
      #     filename: "bin.zip"
      #     # path: downloads
      #     # file: bin.zip

      # Build Docker image
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: SSH Debug
        uses: lhotari/action-upterm@v1

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
