name: c2wasm-api to Heroku CD

on:
  push:
    branches: [master, feat/dockerize-c2wasm-api]

#set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'xrpl-c2wasm-api' }}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:
      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get submodules
        env:
          SSH_KEY_SUBMODULE: ${{secrets.SSH_KEY_C2WASM_API}}

      - name: SSH Debug
        uses: lhotari/action-upterm@v1
        # run: |
        #   eval `ssh-agent -s`
        #   ssh-add - <<< "${SSH_KEY_SUBMODULE}"; git submodule update c2wasm-api --init --recursive

      - name: Download bin.zip
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "eqlabs/xrpl-hooks-compiler"
          version: "tags/v1.3"
          file: "bin.zip"
          target: "./bin.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          unzip -o bin.zip
          cd docker
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
