name: c2wasm-api to Heroku CD
uses: dawidd6/action-download-artifact@v2
with:

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

#set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'xrpl-c2wasm-api' }}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:
      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download release
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: eqlabs/xrpl-hooks-compiler
          tag: "v1.3"
          path: downloads
          file: bin.zpi

      # Build Docker image
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
